return {
    Command = {
        ['carry'] = {
            libanim1 = 'missfinale_c2mcs_1',
			anim1 = 'fin_c2_mcs_1_camman',
			libanim2 = 'nm',
			anim2 = 'firemans_carry',
			distans = 0.15,
			distans2 = 0.27,
			height = 0.63,
			spin = 0.0,	
			length = 100000,
			controlFlagMe = 49,
			controlFlagTarget = 33,
			animFlagTarget = 1,
        },
        ['carry2'] = {
            libanim1 = 'random@shop_tattoo',
			anim1 = '_idle_a',
			libanim2 = 'timetable@ron@ig_3_couch',
			anim2 = 'base',
			distans = 0.1,
			distans2 = 0.05,
			height = 0.8,
			spin = 0.0,		
			length = 100000,
			controlFlagMe = 49,
			controlFlagTarget = 33,
			animFlagTarget = 1,
        },
        ['carry3'] = {
            libanim1 = 'anim@heists@box_carry@',
			anim1 = 'idle',
			libanim2 = 'timetable@reunited@ig_10',
			anim2 = 'base_amanda',
			distans = 0.5,
			distans2 = -0.65,
			height = 0.5,
			spin = 90.0,	
			length = 100000,
			controlFlagMe = 49,
			controlFlagTarget = 33,
			animFlagTarget = 1,
        },
        ['gendong1'] = {
            libanim1 = 'move_m@hiking',
			anim1 = 'idle',
			libanim2 = 'timetable@ron@ig_3_couch',
			anim2 = 'base',
			distans = 0.4,
			distans2 = 0.00,
			height = 1.6,
			spin = 0.0,	
			length = 100000, 
			controlFlagMe = 49, 
			controlFlagTarget = 33,
			animFlagTarget = 1,
        },
        ['gendong2'] = {
            libanim1 = 'amb@world_human_drinking@coffee@male@base',
			anim1 = 'base',
			libanim2 = 'timetable@tracy@ig_14@',
			anim2 = 'ig_14_base_tracy',
			distans = 0.0,
			distans2 = 0.2,
			height = 1.6,
			spin = 0.0,	
			length = 100000,
			controlFlagMe = 49,
			controlFlagTarget = 33,
			animFlagTarget = 1,
        },
    }
}